test gke ci

diff --git a/.github/workflows/pr-test.yml b/.github/workflows/pr-test.yml
--- a/.github/workflows/pr-test.yml
+++ b/.github/workflows/pr-test.yml
@@ -28,29 +28,12 @@ jobs:
 
   e2e-test-1-tpu:
     if: github.event.pull_request.draft == false
-    runs-on: arc-runner-v6e-1
+    runs-on: tpu-runner-v6e-1
     strategy:
       fail-fast: false
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-      - name: Install Python 3.12 and dependencies
-        shell: bash
-        run: |
-          sudo apt update
-          sudo apt install -y software-properties-common
-          sudo add-apt-repository -y ppa:deadsnakes/ppa
-          sudo apt update
-          sudo apt install -y \
-              python3.12 \
-              python3.12-venv \
-              python3.12-dev \
-              python3-pip \
-              git \
-              curl \
-              procps \
-              build-essential
-          python3.12 --version
       - name: Run test
         timeout-minutes: 120
         shell: bash
@@ -62,41 +45,41 @@ jobs:
           bash scripts/killall_sglang.sh
           python test/srt/run_suite.py --suite per-commit-tpu-v6e-1
 
-  e2e-test-4-tpu:
-    if: github.event.pull_request.draft == false
-    runs-on: arc-runner-v6e-4
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Install Python 3.12 and dependencies
-        shell: bash
-        run: |
-          sudo apt update
-          sudo apt install -y software-properties-common
-          sudo add-apt-repository -y ppa:deadsnakes/ppa
-          sudo apt update
-          sudo apt install -y \
-              python3.12 \
-              python3.12-venv \
-              python3.12-dev \
-              python3-pip \
-              git \
-              curl \
-              procps \
-              build-essential
-          python3.12 --version
-      - name: Run test
-        timeout-minutes: 120
-        shell: bash
-        run: |
-          python3.12 -m venv .venv
-          source .venv/bin/activate
-          pip install uv
-          uv pip install -e "python[all]"
-          bash scripts/killall_sglang.sh
-          python test/srt/run_suite.py --suite per-commit-tpu-v6e-4
+  # e2e-test-4-tpu:
+  #   if: github.event.pull_request.draft == false
+  #   runs-on: arc-runner-v6e-4
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Install Python 3.12 and dependencies
+  #       shell: bash
+  #       run: |
+  #         sudo apt update
+  #         sudo apt install -y software-properties-common
+  #         sudo add-apt-repository -y ppa:deadsnakes/ppa
+  #         sudo apt update
+  #         sudo apt install -y \
+  #             python3.12 \
+  #             python3.12-venv \
+  #             python3.12-dev \
+  #             python3-pip \
+  #             git \
+  #             curl \
+  #             procps \
+  #             build-essential
+  #         python3.12 --version
+  #     - name: Run test
+  #       timeout-minutes: 120
+  #       shell: bash
+  #       run: |
+  #         python3.12 -m venv .venv
+  #         source .venv/bin/activate
+  #         pip install uv
+  #         uv pip install -e "python[all]"
+  #         bash scripts/killall_sglang.sh
+  #         python test/srt/run_suite.py --suite per-commit-tpu-v6e-4
   # e2e-test-4-tpu:
   #   if: github.event.pull_request.draft == false
   #   runs-on: tpuv6e-4
@@ -202,21 +185,21 @@ jobs:
   #         CLUSTER_NAME=$(bash scripts/get_cluster_name.sh tpu-v6e-1 ${{ github.ref }} accuracy)
   #         sky exec "$CLUSTER_NAME" -- 'set -e; cd sglang-jax/test/srt; python3 test_eval_accuracy_large.py'
 
-  pr-test-finish:
-    needs: [
-      e2e-test-1-tpu,
-      e2e-test-4-tpu,
-    ]
-    runs-on: arc-runner-cpu
-    steps:
-      - name: Check all dependent job statuses
-        run: |
-          results=(${{ join(needs.*.result, ' ') }})
-          for result in "${results[@]}"; do
-            if [ "$result" = "failure" ] || [ "$result" = "cancelled" ]; then
-              echo "Job failed with result: $result"
-              exit 1
-            fi
-          done
-          echo "All jobs completed successfully"
-          exit 0
+  # pr-test-finish:
+  #   needs: [
+  #     e2e-test-1-tpu,
+  #     e2e-test-4-tpu,
+  #   ]
+  #   runs-on: arc-runner-cpu
+  #   steps:
+  #     - name: Check all dependent job statuses
+  #       run: |
+  #         results=(${{ join(needs.*.result, ' ') }})
+  #         for result in "${results[@]}"; do
+  #           if [ "$result" = "failure" ] || [ "$result" = "cancelled" ]; then
+  #             echo "Job failed with result: $result"
+  #             exit 1
+  #           fi
+  #         done
+  #         echo "All jobs completed successfully"
+  #         exit 0
